version: '2'

services:
  app:
    image: 'dcs:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dcs
      - SPRING_DATASOURCE_USERNAME=dcs
      - SPRING_DATASOURCE_PASSWORD=dcs
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "18080:8080"
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=dcs
      - POSTGRES_PASSWORD=dcs